// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Railway のビルド時点では Postgres 未接続でも `prisma generate` が通るようにする（実行時は実URLが必須）
    url:
      process.env["DATABASE_URL"] ??
      "postgresql://postgres:postgres@127.0.0.1:5432/postgres",
  },
});
